import { Router } from "express";
import userController from "../controllers/user.controllers.js";
const userRouter = Router();
userRouter.post("/register", userController.register);
userRouter.post("/login", userController.login);
userRouter.post("/token", userController.getRefToken);
userRouter.post("/logout", userController.logout);
userRouter.post("/send-otp", userController.sendOtp);
userRouter.put("/change-password", userController.changePasswordWithOtp);
userRouter.put("/change-info", userController.changeInfo);
export default userRouter;
